version: '2.4'
services:
  db:
    image: mysql
    container_name: springboot_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devdojo_springboot_data:/var/lib/mysql

volumes:
  devdojo_springboot_data: